version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    env_file:
      - /root/git/docker/site/api.env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - /root/git/docker/site/api.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
