version: '3'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    env_file: .env
    #environment:
    #  WORDPRESS_DB_HOST: db
    #  WORDPRESS_DB_USER: exampleuser
    #  WORDPRESS_DB_PASSWORD: examplepass
    #  WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - /root/git/docker/site/api.env
    #environment:
    #  MYSQL_DATABASE: exampledb
    #  MYSQL_USER: exampleuser
    #  MYSQL_PASSWORD: examplepass
    #  MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
