version: "3"
services:
  api:
    build:
      context: .
      dockerfile: . dockerfile
    restart: always
    container_name: api
    volumes:
    - web:/usr/share/nginx/html
    ports:
    - 1234:80
    networks:
    - myNetworks

#Если нужно создать сеть
networks:
  myNetworks:
    driver: bridge

volumes:
  web:
